spring:
    datasource:
        url: jdbc:mysql://localhost:3306/real_land?useSSL=false
        username: real_user
        password: password
        driver-class-name: com.mysql.cj.jdbc.Driver
        dbcp2:
            min-idle: 8
            max-idle: 8
            max-total: 10
            initial-size: 5
            max-wait-millis: 10000
    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      show-sql: false

server:
    port: 8080
    servlet:
        context-path: /realland
