INSERT INTO `role` (`role_id`, `created_date`, `description`, `type_id`, `name`, `status`) VALUES ('1', NOW(), 'View User Profile', '7', 'Profile -> View', '2');
INSERT INTO `role` (`role_id`, `created_date`, `description`, `type_id`, `name`, `status`) VALUES ('2', NOW(), 'Update Profile', '7', 'Profile -> Update', '2');
INSERT INTO `role` (`role_id`, `created_date`, `description`, `type_id`, `name`, `status`) VALUES ('3', NOW(), 'Change Password', '7', 'Change Password', '2');
INSERT INTO `role` (`role_id`, `created_date`, `description`, `type_id`, `name`, `status`) VALUES ('4', NOW(), 'Admin -> View Grid', '7', 'Admin -> View Grid', '2');
INSERT INTO `role` (`role_id`, `created_date`, `description`, `type_id`, `name`, `status`) VALUES ('5', NOW(), 'Admin -> Add New', '7', 'Admin -> Add New', '2');
INSERT INTO `role` (`role_id`, `created_date`, `description`, `type_id`, `name`, `status`) VALUES ('6', NOW(), 'Admin -> Update', '7', 'Admin -> Update', '2');
INSERT INTO `role` (`role_id`, `created_date`, `description`, `type_id`, `name`, `status`) VALUES ('7', NOW(), 'Admin -> Approve', '7', 'Admin -> Approve', '2');
INSERT INTO `role` (`role_id`, `created_date`, `description`, `type_id`, `name`, `status`) VALUES ('8', NOW(), 'Admin -> Suspend', '7', 'Admin -> Suspend', '2');
INSERT INTO `role` (`role_id`, `created_date`, `description`, `type_id`, `name`, `status`) VALUES ('9', NOW(), 'Admin -> Delete', '7', 'Admin -> Delete', '2');
INSERT INTO `role` (`role_id`, `created_date`, `description`, `type_id`, `name`, `status`) VALUES ('21', NOW(), 'Role Group -> View Grid', '7', 'Role Group -> View Grid', '2');
INSERT INTO `role` (`role_id`, `created_date`, `description`, `type_id`, `name`, `status`) VALUES ('22', NOW(), 'Role Group -> Add New', '7', 'Role Group -> Add New', '2');
INSERT INTO `role` (`role_id`, `created_date`, `description`, `type_id`, `name`, `status`) VALUES ('23', NOW(), 'Role Group -> Update', '7', 'Role Group -> Update', '2');
INSERT INTO `role` (`role_id`, `created_date`, `description`, `type_id`, `name`, `status`) VALUES ('24', NOW(), 'Role Group -> Approve', '7', 'Role Group -> Approve', '2');
INSERT INTO `role` (`role_id`, `created_date`, `description`, `type_id`, `name`, `status`) VALUES ('25', NOW(), 'Role Group -> Suspend', '7', 'Role Group -> Suspend', '2');
INSERT INTO `role` (`role_id`, `created_date`, `description`, `type_id`, `name`, `status`) VALUES ('26', NOW(), 'Role Group -> Delete', '7', 'Role Group -> Delete', '2');


INSERT INTO `role` (`role_id`, `created_date`, `description`, `type_id`, `name`, `status`) VALUES ('101', NOW(), 'Merchant -> View Grid', '1', 'Merchant -> View Grid', '2');
INSERT INTO `role` (`role_id`, `created_date`, `description`, `type_id`, `name`, `status`) VALUES ('102', NOW(), 'Merchant -> Add New', '1', 'Merchant -> Add New', '2');
INSERT INTO `role` (`role_id`, `created_date`, `description`, `type_id`, `name`, `status`) VALUES ('103', NOW(), 'Merchant -> Update', '1', 'Merchant -> Update', '2');
INSERT INTO `role` (`role_id`, `created_date`, `description`, `type_id`, `name`, `status`) VALUES ('104', NOW(), 'Merchant -> Approve', '1', 'Merchant -> Approve', '2');
INSERT INTO `role` (`role_id`, `created_date`, `description`, `type_id`, `name`, `status`) VALUES ('105', NOW(), 'Merchant -> Suspend', '1', 'Merchant -> Suspend', '2');
INSERT INTO `role` (`role_id`, `created_date`, `description`, `type_id`, `name`, `status`) VALUES ('106', NOW(), 'Merchant -> Delete', '1', 'Merchant -> Delete', '2');
INSERT INTO `role` (`role_id`, `created_date`, `description`, `type_id`, `name`, `status`) VALUES ('201', NOW(), 'Client -> View Grid', '1', 'Client -> View Grid', '2');
INSERT INTO `role` (`role_id`, `created_date`, `description`, `type_id`, `name`, `status`) VALUES ('202', NOW(), 'Client -> Add New', '1', 'Client -> Add New', '2');
INSERT INTO `role` (`role_id`, `created_date`, `description`, `type_id`, `name`, `status`) VALUES ('203', NOW(), 'Client -> Update', '1', 'Client -> Update', '2');
INSERT INTO `role` (`role_id`, `created_date`, `description`, `type_id`, `name`, `status`) VALUES ('204', NOW(), 'Client -> Approve', '1', 'Client -> Approve', '2');
INSERT INTO `role` (`role_id`, `created_date`, `description`, `type_id`, `name`, `status`) VALUES ('205', NOW(), 'Client -> Suspend', '1', 'Client -> Suspend', '2');
INSERT INTO `role` (`role_id`, `created_date`, `description`, `type_id`, `name`, `status`) VALUES ('206', NOW(), 'Client -> Delete', '1', 'Client -> Delete', '2');

INSERT INTO `role` (`role_id`, `created_date`, `description`, `type_id`, `name`, `status`) VALUES ('301', NOW(), 'Province -> View Grid', '1', 'Province -> View Grid', '2');
INSERT INTO `role` (`role_id`, `created_date`, `description`, `type_id`, `name`, `status`) VALUES ('302', NOW(), 'Province -> Add New', '1', 'Province -> Add New', '2');
INSERT INTO `role` (`role_id`, `created_date`, `description`, `type_id`, `name`, `status`) VALUES ('303', NOW(), 'Province -> Update', '1', 'Province -> Update', '2');
INSERT INTO `role` (`role_id`, `created_date`, `description`, `type_id`, `name`, `status`) VALUES ('304', NOW(), 'Province -> Approve', '1', 'Province -> Approve', '2');
INSERT INTO `role` (`role_id`, `created_date`, `description`, `type_id`, `name`, `status`) VALUES ('305', NOW(), 'Province -> Suspend', '1', 'Province -> Suspend', '2');
INSERT INTO `role` (`role_id`, `created_date`, `description`, `type_id`, `name`, `status`) VALUES ('306', NOW(), 'Province -> Delete', '1', 'Province -> Delete', '2');
INSERT INTO `role` (`role_id`, `created_date`, `description`, `type_id`, `name`, `status`) VALUES ('307', NOW(), 'District -> View Grid', '1', 'District -> View Grid', '2');
INSERT INTO `role` (`role_id`, `created_date`, `description`, `type_id`, `name`, `status`) VALUES ('308', NOW(), 'District -> Add New', '1', 'District -> Add New', '2');
INSERT INTO `role` (`role_id`, `created_date`, `description`, `type_id`, `name`, `status`) VALUES ('309', NOW(), 'District -> Update', '1', 'District -> Update', '2');
INSERT INTO `role` (`role_id`, `created_date`, `description`, `type_id`, `name`, `status`) VALUES ('310', NOW(), 'District -> Approve', '1', 'District -> Approve', '2');
INSERT INTO `role` (`role_id`, `created_date`, `description`, `type_id`, `name`, `status`) VALUES ('311', NOW(), 'District -> Suspend', '1', 'District -> Suspend', '2');
INSERT INTO `role` (`role_id`, `created_date`, `description`, `type_id`, `name`, `status`) VALUES ('312', NOW(), 'District -> Delete', '1', 'District -> Delete', '2');
INSERT INTO `role` (`role_id`, `created_date`, `description`, `type_id`, `name`, `status`) VALUES ('313', NOW(), 'City -> View Grid', '1', 'City -> View Grid', '2');
INSERT INTO `role` (`role_id`, `created_date`, `description`, `type_id`, `name`, `status`) VALUES ('314', NOW(), 'City -> Add New', '1', 'City -> Add New', '2');
INSERT INTO `role` (`role_id`, `created_date`, `description`, `type_id`, `name`, `status`) VALUES ('315', NOW(), 'City -> Update', '1', 'City -> Update', '2');
INSERT INTO `role` (`role_id`, `created_date`, `description`, `type_id`, `name`, `status`) VALUES ('316', NOW(), 'City -> Approve', '1', 'City -> Approve', '2');
INSERT INTO `role` (`role_id`, `created_date`, `description`, `type_id`, `name`, `status`) VALUES ('317', NOW(), 'City -> Suspend', '1', 'City -> Suspend', '2');
INSERT INTO `role` (`role_id`, `created_date`, `description`, `type_id`, `name`, `status`) VALUES ('318', NOW(), 'City -> Delete', '1', 'City -> Delete', '2');
INSERT INTO `role` (`role_id`, `created_date`, `description`, `type_id`, `name`, `status`) VALUES ('319', NOW(), 'Property Amenity -> View Grid', '1', 'Property Amenity -> View Grid', '2');
INSERT INTO `role` (`role_id`, `created_date`, `description`, `type_id`, `name`, `status`) VALUES ('320', NOW(), 'Property Amenity -> Add New', '1', 'Property Amenity -> Add New', '2');
INSERT INTO `role` (`role_id`, `created_date`, `description`, `type_id`, `name`, `status`) VALUES ('321', NOW(), 'Property Amenity -> Update', '1', 'Property Amenity -> Update', '2');
INSERT INTO `role` (`role_id`, `created_date`, `description`, `type_id`, `name`, `status`) VALUES ('322', NOW(), 'Property Amenity -> Approve', '1', 'Property Amenity -> Approve', '2');
INSERT INTO `role` (`role_id`, `created_date`, `description`, `type_id`, `name`, `status`) VALUES ('323', NOW(), 'Property Amenity -> Suspend', '1', 'Property Amenity -> Suspend', '2');
INSERT INTO `role` (`role_id`, `created_date`, `description`, `type_id`, `name`, `status`) VALUES ('324', NOW(), 'Property Amenity -> Delete', '1', 'Property Amenity -> Delete', '2');
INSERT INTO `role` (`role_id`, `created_date`, `description`, `type_id`, `name`, `status`) VALUES ('325', NOW(), 'Property -> View Grid - System User', '1', 'Property -> View Grid - System User', '2');
INSERT INTO `role` (`role_id`, `created_date`, `description`, `type_id`, `name`, `status`) VALUES ('326', NOW(), 'Property -> Update - System User', '1', 'Property -> Update - System User', '2');
INSERT INTO `role` (`role_id`, `created_date`, `description`, `type_id`, `name`, `status`) VALUES ('327', NOW(), 'Property -> Approve - System User', '1', 'Property -> Approve - System User', '2');
INSERT INTO `role` (`role_id`, `created_date`, `description`, `type_id`, `name`, `status`) VALUES ('328', NOW(), 'Property -> Suspend - System User', '1', 'Property -> Suspend - System User', '2');
INSERT INTO `role` (`role_id`, `created_date`, `description`, `type_id`, `name`, `status`) VALUES ('329', NOW(), 'Property -> Delete - System User', '1', 'Property -> Delete - System User', '2');
INSERT INTO `role` (`role_id`, `created_date`, `description`, `type_id`, `name`, `status`) VALUES ('330', NOW(), 'System Parameter -> View Grid', '1', 'System Parameter -> View Grid', '2');
INSERT INTO `role` (`role_id`, `created_date`, `description`, `type_id`, `name`, `status`) VALUES ('331', NOW(), 'System Parameter -> Add New', '1', 'System Parameter -> Add New', '2');
INSERT INTO `role` (`role_id`, `created_date`, `description`, `type_id`, `name`, `status`) VALUES ('332', NOW(), 'System Parameter -> Update', '1', 'System Parameter -> Update', '2');
INSERT INTO `role` (`role_id`, `created_date`, `description`, `type_id`, `name`, `status`) VALUES ('333', NOW(), 'System Statement -> View Grid', '1', 'System Statement -> View Grid', '2');
INSERT INTO `role` (`role_id`, `created_date`, `description`, `type_id`, `name`, `status`) VALUES ('334', NOW(), 'System Statement -> Add New', '1', 'System Statement -> Add New', '2');
INSERT INTO `role` (`role_id`, `created_date`, `description`, `type_id`, `name`, `status`) VALUES ('335', NOW(), 'System Statement -> Update', '1', 'System Statement -> Update', '2');

-- sp

INSERT INTO `role` (`role_id`, `created_date`, `description`, `type_id`, `name`, `status`) VALUES ('1001', NOW(), 'Property Ad -> View Grid', '2', 'Property Ad -> View Grid', '2');
INSERT INTO `role` (`role_id`, `created_date`, `description`, `type_id`, `name`, `status`) VALUES ('1002', NOW(), 'Property Ad -> Add New', '2', 'Property Ad -> Add New', '2');
INSERT INTO `role` (`role_id`, `created_date`, `description`, `type_id`, `name`, `status`) VALUES ('1003', NOW(), 'Property Ad -> Update', '2', 'Property Ad -> Update', '2');
INSERT INTO `role` (`role_id`, `created_date`, `description`, `type_id`, `name`, `status`) VALUES ('1004', NOW(), 'Property Ad -> Approve', '2', 'Property Ad -> Approve', '2');
INSERT INTO `role` (`role_id`, `created_date`, `description`, `type_id`, `name`, `status`) VALUES ('1005', NOW(), 'Property Ad -> Suspend', '2', 'Property Ad -> Suspend', '2');
INSERT INTO `role` (`role_id`, `created_date`, `description`, `type_id`, `name`, `status`) VALUES ('1006', NOW(), 'Property Ad -> Delete', '2', 'Property Ad -> Delete', '2');
